### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [Piratvc/AlgorytmTest#1]
Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by Piratvc** [comment]
Кол-во групп 206926
21.588 секунд

**Comment by alexkoss** [comment]
Ответ неправильный.

**Comment by Piratvc** [comment]
ок еще поковыряю посмотрю

**Comment by Piratvc** [comment]
Добавил паттерны проверки строк, результат:
Кол-во групп 24304
14.185 секунд

**Comment by alexkoss** [comment]
Снова ответ неправильный.

**Comment by alexkoss** [comment]
Попробуете ещё раз?

**Comment by Piratvc** [comment]
да, копаюсь

**Comment by Piratvc** [comment]
Еще попытка
Кол-во групп 24349
14.471 seconds

**Comment by alexkoss** [comment]
Правильный ответ 105036.

**Comment by alexkoss** [comment]
Спасибо за уделённое время.
